exports.afk = require('./afk')
exports.ind = require('./modules')
exports.premium = require('./premium')
exports.limit = require('./limit')
exports.register = require('./register.js')
exports.reminder = require('./reminder')
exports.daily = require('./daily')
exports.warnss = require('./warn')
